namespace OpenDotaApi.Enums
{
    public enum EnumConstants
    {
        Abilities,
        AbilityIds,
        AbilityKeys,
        Ancients,
        ChatWheel,
        Cluster,
        Countries,
        GameMode,
        HeroAbilities,
        HeroLore,
        HeroNames,
        Heroes,
        ItemColors,
        ItemGroups,
        ItemIds,
        Items,
        LobbyType,
        NeutralAbilities,
        OrderTypes,
        Patch,
        Patchnotes,
        PermanentBuffs,
        PlayerColors,
        Region,
        Skillshots,
        XpLevel
    }
}